/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as GuidesSousVideRouteImport } from "./routes/guides/sous-vide";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const GuidesSousVideRoute = GuidesSousVideRouteImport.update({
  id: "/guides/sous-vide",
  path: "/guides/sous-vide",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/guides/sous-vide": typeof GuidesSousVideRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/guides/sous-vide": typeof GuidesSousVideRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/guides/sous-vide": typeof GuidesSousVideRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/guides/sous-vide";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/guides/sous-vide";
  id: "__root__" | "/" | "/guides/sous-vide";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GuidesSousVideRoute: typeof GuidesSousVideRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/guides/sous-vide": {
      id: "/guides/sous-vide";
      path: "/guides/sous-vide";
      fullPath: "/guides/sous-vide";
      preLoaderRoute: typeof GuidesSousVideRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesSousVideRoute: GuidesSousVideRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
